import { Reel, Interaction, Category, Difficulty, Format } from '../shared/types.js';

export const DEMO_USER = {
  id: '00000000-0000-0000-0000-000000000001',
  display_name: 'Alex Chen (CS Student)',
  created_at: new Date('2026-08-01T00:00:00Z').toISOString(),
};

/**
 * 8 Seeded Interaction Reels (is_candidate = false)
 * Represents what the student has already watched.
 * Contains the classic Trap Sequence (Reels 1-4).
 */
export const SEED_INTERACTION_REELS: Reel[] = [
  {
    id: '10000000-0000-0000-0000-000000000001',
    title: 'POV: your code compiles on the first try',
    description: 'Relatable developer meme celebrating rare instant compilation in Java.',
    transcript: 'POV: you just wrote 400 lines of Java with generics, Maven plugins, and Spring beans, hit build, and zero compiler errors appear on screen. Pure euphoria.',
    category: 'Java',
    difficulty: 'Beginner',
    format: 'Meme',
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    source_url: 'https://youtube.com/shorts/sample1',
    duration_seconds: 25,
    educational_value: 20,
    hype_score: 25,
    is_candidate: false,
    created_at: new Date('2026-08-10T10:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000002',
    title: 'A day in my life as a backend engineer at a fintech startup',
    description: 'Realistic behind-the-scenes engineering workflow, standups, and architecture reviews.',
    transcript: 'Starting my day at 9 AM triage in Slack, debugging microservice latency spikes in Grafana, reviewing a pull request for idempotent payment webhooks, and our 2 PM distributed systems whiteboard session.',
    category: 'Career',
    difficulty: 'Intermediate',
    format: 'Vlog',
    thumbnail_url: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    source_url: 'https://youtube.com/shorts/sample2',
    duration_seconds: 45,
    educational_value: 55,
    hype_score: 35,
    is_candidate: false,
    created_at: new Date('2026-08-11T11:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000003',
    title: 'Interviewer: reverse a linked list. Me:',
    description: 'Humorous take on technical coding interview pressure and algorithm memorization vs intuition.',
    transcript: 'Interviewer asks me to reverse a singly linked list in-place in O(1) space. My brain: do I swap pointers or allocate a dummy node? When three pointers turn into a recursive nightmare.',
    category: 'DSA',
    difficulty: 'Beginner',
    format: 'Meme',
    thumbnail_url: 'https://images.unsplash.com/photo-1516116211227-bbc13c4155b9?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    source_url: 'https://youtube.com/shorts/sample3',
    duration_seconds: 30,
    educational_value: 30,
    hype_score: 20,
    is_candidate: false,
    created_at: new Date('2026-08-12T12:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000004',
    title: 'M3 MacBook Pro vs ThinkPad X1 for developers',
    description: 'Hardware benchmark comparison specifically comparing Docker container compilation and local LLM performance.',
    transcript: 'We compiled a massive Rust and Go monorepo across 20 parallel Docker containers. Battery life on Apple Silicon remains unbeaten, but the Linux kernel tooling on the ThinkPad X1 carbon is rock solid.',
    category: 'Hardware',
    difficulty: 'Intermediate',
    format: 'Comparison',
    thumbnail_url: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    source_url: 'https://youtube.com/shorts/sample4',
    duration_seconds: 50,
    educational_value: 45,
    hype_score: 40,
    is_candidate: false,
    created_at: new Date('2026-08-13T13:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000005',
    title: 'Coffee setup for 3 AM coding sessions',
    description: 'Casual lifestyle and espresso brewing routine during university hackathons.',
    transcript: 'Dialing in an Ethiopian single origin pour-over at 3 AM to survive the university hackathon submission deadline. Caffeine levels at maximum.',
    category: 'Career',
    difficulty: 'Beginner',
    format: 'Vlog',
    thumbnail_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    source_url: 'https://youtube.com/shorts/sample5',
    duration_seconds: 28,
    educational_value: 10,
    hype_score: 20,
    is_candidate: false,
    created_at: new Date('2026-08-14T14:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000006',
    title: 'Building a custom 65% mechanical keyboard',
    description: 'Soldering switches, lubing stabilizers, and custom keycaps for coding ergonomics.',
    transcript: 'Lubing Gateron Oil Kings and installing tape mod on a custom aluminum gasket mounted board for the deepest typing acoustic profile while writing code.',
    category: 'Hardware',
    difficulty: 'Beginner',
    format: 'Tutorial',
    thumbnail_url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    source_url: 'https://youtube.com/shorts/sample6',
    duration_seconds: 40,
    educational_value: 25,
    hype_score: 30,
    is_candidate: false,
    created_at: new Date('2026-08-15T15:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000007',
    title: 'CSS centering memes that never die',
    description: 'Short comedy sketch on flexbox and grid vs margin auto.',
    transcript: '2010: how do I center a div with float and tables? 2026: place-items: center in one line. Why did we suffer for 15 years?',
    category: 'WebDev',
    difficulty: 'Beginner',
    format: 'Meme',
    thumbnail_url: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    source_url: 'https://youtube.com/shorts/sample7',
    duration_seconds: 22,
    educational_value: 25,
    hype_score: 15,
    is_candidate: false,
    created_at: new Date('2026-08-16T16:00:00Z').toISOString(),
  },
  {
    id: '10000000-0000-0000-0000-000000000008',
    title: 'The sound of 100 enterprise servers booting up',
    description: 'Ambient data center audio and rack inspection.',
    transcript: 'That unmistakable high-rpm fan roar when 40 dual-socket rackmount servers boot up in a cold-aisle data center environment.',
    category: 'DevOps',
    difficulty: 'Beginner',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    source_url: 'https://youtube.com/shorts/sample8',
    duration_seconds: 20,
    educational_value: 30,
    hype_score: 25,
    is_candidate: false,
    created_at: new Date('2026-08-17T17:00:00Z').toISOString(),
  },
];

/**
 * Seeded Demo User Interactions for the Trap Sequence
 */
export const SEED_DEMO_INTERACTIONS: Interaction[] = [
  {
    id: '20000000-0000-0000-0000-000000000001',
    user_id: DEMO_USER.id,
    reel_id: SEED_INTERACTION_REELS[0].id, // Java meme
    watch_percentage: 95,
    liked: true,
    saved: false,
    shared: true,
    timestamp: new Date('2026-08-18T08:15:00Z').toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000002',
    user_id: DEMO_USER.id,
    reel_id: SEED_INTERACTION_REELS[1].id, // SWE fintech vlog
    watch_percentage: 90,
    liked: true,
    saved: true,
    shared: false,
    timestamp: new Date('2026-08-18T08:20:00Z').toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000003',
    user_id: DEMO_USER.id,
    reel_id: SEED_INTERACTION_REELS[2].id, // Linked list joke
    watch_percentage: 85,
    liked: false,
    saved: true,
    shared: false,
    timestamp: new Date('2026-08-18T08:25:00Z').toISOString(),
  },
  {
    id: '20000000-0000-0000-0000-000000000004',
    user_id: DEMO_USER.id,
    reel_id: SEED_INTERACTION_REELS[3].id, // MacBook vs ThinkPad
    watch_percentage: 88,
    liked: true,
    saved: false,
    shared: false,
    timestamp: new Date('2026-08-18T08:30:00Z').toISOString(),
  },
];

/**
 * 25-30 Candidate Recommendation Reels (is_candidate = true)
 * Spans AI, DSA, Java, HLD, Cybersecurity, Cloud, Hardware, Career, WebDev, DevOps.
 * Includes:
 * - High-value HLD/System Design target reels (ideal recommendation for trap scenario)
 * - Clickbait / High Hype penalty test reels
 * - Varied difficulties across all domains
 */
export const SEED_CANDIDATE_REELS: Reel[] = [
  // --- High-Value HLD Target Reels (Ideal for Trap Scenario) ---
  {
    id: '30000000-0000-0000-0000-000000000001',
    title: 'System Design Basics: How Instagram Handles a Billion Users',
    description: 'Architectural breakdown of feed generation, fan-out on write vs read, and Redis caching layers.',
    transcript: 'When a user opens Instagram, querying a relational database for millions of followers would crash production. In this video, we dissect the hybrid fan-out model: write fan-out for regular users and read fan-out for celebrities with Redis cluster caching and async Celery queues.',
    category: 'HLD',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    source_url: 'https://youtube.com/watch?v=hld_insta_arch',
    duration_seconds: 60,
    educational_value: 94,
    hype_score: 15,
    is_candidate: true,
    created_at: new Date('2026-08-17T09:00:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000002',
    title: 'Designing a Distributed Cache with Consistent Hashing',
    description: 'Mathematical foundation and implementation of consistent hashing to prevent cache stampedes.',
    transcript: 'Standard modulo hashing causes near 100% cache invalidation when scaling nodes. Consistent hashing maps both servers and keys onto a virtual 360 ring, ensuring minimal key migration and predictable cluster rebalancing.',
    category: 'HLD',
    difficulty: 'Intermediate',
    format: 'Tutorial',
    thumbnail_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    source_url: 'https://youtube.com/watch?v=hld_consistent_hash',
    duration_seconds: 55,
    educational_value: 92,
    hype_score: 10,
    is_candidate: true,
    created_at: new Date('2026-08-17T09:15:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000003',
    title: 'Rate Limiter Algorithms: Token Bucket vs Leaky Bucket',
    description: 'Deep dive into API rate limiting algorithms and concurrency control in Redis.',
    transcript: 'To defend your backend against DoS spikes and client retries, Token Bucket provides burst tolerance with simple integer decrements, while Leaky Bucket guarantees uniform downstream flow rates.',
    category: 'HLD',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    source_url: 'https://youtube.com/watch?v=hld_rate_limiter',
    duration_seconds: 48,
    educational_value: 90,
    hype_score: 12,
    is_candidate: true,
    created_at: new Date('2026-08-17T09:30:00Z').toISOString(),
  },

  // --- High Hype / Low Educational Value Penalty Test Reels ---
  {
    id: '30000000-0000-0000-0000-000000000004',
    title: '10 AI tools that will get you hired in 2026 (NO CODING!)',
    description: 'Sensationalist career video promising overnight software engineering jobs using generic prompt templates.',
    transcript: 'Stop learning coding in 2026! Software engineers are dead. Here are 10 insane AI prompt generators that write full stack apps automatically so you can get hired at FAANG in 7 days without knowing any algorithms.',
    category: 'AI',
    difficulty: 'Beginner',
    format: 'News',
    thumbnail_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    source_url: 'https://youtube.com/watch?v=hype_ai_10tools',
    duration_seconds: 35,
    educational_value: 15,
    hype_score: 95,
    is_candidate: true,
    created_at: new Date('2026-08-17T09:45:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000005',
    title: 'Make $500k in 30 days as a Vibe Coder (Secret Method)',
    description: 'Get-rich-quick career hype video emphasizing passive income shortcuts over engineering fundamentals.',
    transcript: 'If you are not making half a million dollars right now writing two sentences in an AI terminal, you are falling behind. Watch this secret trick before big tech bans it.',
    category: 'Career',
    difficulty: 'Beginner',
    format: 'Vlog',
    thumbnail_url: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    source_url: 'https://youtube.com/watch?v=hype_vibecoder',
    duration_seconds: 40,
    educational_value: 8,
    hype_score: 98,
    is_candidate: true,
    created_at: new Date('2026-08-17T10:00:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000006',
    title: 'Why JavaScript is DEAD and what replaces it tomorrow',
    description: 'Sensationalist framework debate video with inflated clickbait claims.',
    transcript: 'Every single company is abandoning JavaScript tonight. If you write one more line of TypeScript, your career is ruined. Here is why you must rewrite everything in this unknown framework.',
    category: 'WebDev',
    difficulty: 'Beginner',
    format: 'News',
    thumbnail_url: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    source_url: 'https://youtube.com/watch?v=hype_js_dead',
    duration_seconds: 30,
    educational_value: 20,
    hype_score: 92,
    is_candidate: true,
    created_at: new Date('2026-08-17T10:15:00Z').toISOString(),
  },

  // --- DSA Candidates (Beginner, Intermediate, Advanced) ---
  {
    id: '30000000-0000-0000-0000-000000000007',
    title: 'Dynamic Programming: Mastering 0/1 Knapsack Intuition',
    description: 'Visual state-space reduction and recurrence relation derivation for 0/1 Knapsack.',
    transcript: 'Stop memorizing table grids. Dynamic programming is simply recursion with memoized sub-problems. We derive the choice tree: include the item or exclude it, leading directly to the 2D DP array.',
    category: 'DSA',
    difficulty: 'Intermediate',
    format: 'Tutorial',
    thumbnail_url: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    source_url: 'https://youtube.com/watch?v=dsa_dp_knapsack',
    duration_seconds: 52,
    educational_value: 91,
    hype_score: 10,
    is_candidate: true,
    created_at: new Date('2026-08-17T10:30:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000008',
    title: 'Graph Traversal: When to pick BFS vs DFS in Coding Interviews',
    description: 'Practical taxonomy for graph exploration, shortest paths on unweighted graphs vs cycle detection.',
    transcript: 'BFS uses a queue and guarantees the shortest path on unweighted graphs. DFS uses a stack or call stack recursion, making it ideal for topological sorting and connected components.',
    category: 'DSA',
    difficulty: 'Beginner',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    source_url: 'https://youtube.com/watch?v=dsa_bfs_dfs',
    duration_seconds: 42,
    educational_value: 88,
    hype_score: 12,
    is_candidate: true,
    created_at: new Date('2026-08-17T10:45:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000009',
    title: 'B-Trees & LSM-Trees: How Modern Databases Store Data on Disk',
    description: 'Comparison of write-heavy LSM trees in Cassandra/RocksDB vs read-optimized B+ Trees in Postgres.',
    transcript: 'B+ trees minimize random disk I/O via high branching factors. Log-Structured Merge (LSM) trees optimize for sequential writes via in-memory memtables and background SSTable compaction.',
    category: 'DSA',
    difficulty: 'Advanced',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    source_url: 'https://youtube.com/watch?v=dsa_btree_lsm',
    duration_seconds: 58,
    educational_value: 95,
    hype_score: 8,
    is_candidate: true,
    created_at: new Date('2026-08-17T11:00:00Z').toISOString(),
  },

  // --- AI / Machine Learning Foundations ---
  {
    id: '30000000-0000-0000-0000-000000000010',
    title: 'Attention Mechanism Explained with Matrix Math',
    description: 'Step-by-step query, key, value matrix multiplication in the Transformer architecture.',
    transcript: 'The core of modern LLMs is self-attention: taking input vectors, projecting into Q, K, V matrices, calculating softmax of QK transpose over square root of d_k, and multiplying by V.',
    category: 'AI',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1677442136019-21780efad99a?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    source_url: 'https://youtube.com/watch?v=ai_transformer_math',
    duration_seconds: 50,
    educational_value: 93,
    hype_score: 22,
    is_candidate: true,
    created_at: new Date('2026-08-17T11:15:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000011',
    title: 'Vector Databases & Cosine Similarity in 60 Seconds',
    description: 'How high-dimensional embedding spaces enable semantic RAG search.',
    transcript: 'Embeddings convert text into dense vectors of floating point numbers. Vector databases index these embeddings using HNSW graphs so we can query millions of chunks in milliseconds using cosine similarity.',
    category: 'AI',
    difficulty: 'Beginner',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    source_url: 'https://youtube.com/watch?v=ai_vectordb_rag',
    duration_seconds: 45,
    educational_value: 86,
    hype_score: 30,
    is_candidate: true,
    created_at: new Date('2026-08-17T11:30:00Z').toISOString(),
  },

  // --- Cybersecurity Candidates ---
  {
    id: '30000000-0000-0000-0000-000000000012',
    title: 'How JWT Authentication Fails in Production',
    description: 'Common JSON Web Token vulnerabilities: algorithmic confusion, missing expiry revocation, and localStorage XSS.',
    transcript: 'Storing JWTs in localStorage exposes users to cross-site scripting (XSS). In this video, we review secure HttpOnly cookie storage, short-lived access tokens, and server-side refresh token rotation.',
    category: 'Cybersecurity',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    source_url: 'https://youtube.com/watch?v=sec_jwt_vulnerabilities',
    duration_seconds: 48,
    educational_value: 90,
    hype_score: 18,
    is_candidate: true,
    created_at: new Date('2026-08-17T11:45:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000013',
    title: 'SQL Injection: From Vulnerable Query to Database Dump',
    description: 'Demonstrating parameterized queries vs string concatenation risks.',
    transcript: 'Concatenating user input directly into SQL strings allows attackers to inject tautologies like OR 1=1. Always use prepared statements and parameterized query drivers at the ORM layer.',
    category: 'Cybersecurity',
    difficulty: 'Beginner',
    format: 'Tutorial',
    thumbnail_url: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    source_url: 'https://youtube.com/watch?v=sec_sqli_demo',
    duration_seconds: 38,
    educational_value: 85,
    hype_score: 20,
    is_candidate: true,
    created_at: new Date('2026-08-17T12:00:00Z').toISOString(),
  },

  // --- Cloud & DevOps Candidates ---
  {
    id: '30000000-0000-0000-0000-000000000014',
    title: 'Docker Internals: Namespaces and Cgroups Under the Hood',
    description: 'Explaining Linux kernel primitives that make container isolation possible without virtual machines.',
    transcript: 'Containers are not lightweight virtual machines; they are ordinary Linux processes isolated by kernel cgroups for resource limits and namespaces for PID, mount, and network partitioning.',
    category: 'DevOps',
    difficulty: 'Advanced',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    source_url: 'https://youtube.com/watch?v=devops_docker_internals',
    duration_seconds: 54,
    educational_value: 94,
    hype_score: 10,
    is_candidate: true,
    created_at: new Date('2026-08-17T12:15:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000015',
    title: 'Kubernetes Pod Networking: Flannel vs Calico Explained',
    description: 'Overlay networks, VXLAN encapsulation, and BGP routing across Kubernetes worker nodes.',
    transcript: 'How do pods communicate across physical nodes with flat IP addressing? Flannel uses VXLAN packet encapsulation, while Calico programs BGP routes directly into the Linux routing table.',
    category: 'Cloud',
    difficulty: 'Advanced',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    source_url: 'https://youtube.com/watch?v=cloud_k8s_networking',
    duration_seconds: 52,
    educational_value: 92,
    hype_score: 12,
    is_candidate: true,
    created_at: new Date('2026-08-17T12:30:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000016',
    title: 'Terraform State Management Best Practices in AWS',
    description: 'S3 remote backend, DynamoDB state locking, and directory modularization.',
    transcript: 'Never commit terraform.tfstate to Git. Use an Amazon S3 remote backend with server-side encryption and DynamoDB table locks to prevent concurrent infrastructure mutations.',
    category: 'Cloud',
    difficulty: 'Intermediate',
    format: 'Tutorial',
    thumbnail_url: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4',
    source_url: 'https://youtube.com/watch?v=cloud_terraform_aws',
    duration_seconds: 44,
    educational_value: 87,
    hype_score: 15,
    is_candidate: true,
    created_at: new Date('2026-08-17T12:45:00Z').toISOString(),
  },

  // --- Java & Backend Candidates ---
  {
    id: '30000000-0000-0000-0000-000000000017',
    title: 'Java Virtual Threads (Project Loom): 1 Million Threads Benchmark',
    description: 'How lightweight user-mode virtual threads change high-throughput concurrent I/O.',
    transcript: 'Platform threads map 1:1 to OS threads and consume roughly 1MB of stack memory. Java 21 Virtual Threads are managed by the JVM carrier threads, allowing millions of concurrent network socket connections.',
    category: 'Java',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    source_url: 'https://youtube.com/watch?v=java_virtual_threads',
    duration_seconds: 47,
    educational_value: 89,
    hype_score: 24,
    is_candidate: true,
    created_at: new Date('2026-08-17T13:00:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000018',
    title: 'Spring Boot 3 + GraalVM Native Images: Zero to 50ms Startup',
    description: 'Ahead-Of-Time (AOT) compilation and memory footprint reduction for serverless microservices.',
    transcript: 'Standard JVM initialization takes seconds due to reflection and classloading. GraalVM native image compilation compiles Java bytecode ahead of time into a native machine binary that starts in 40ms.',
    category: 'Java',
    difficulty: 'Advanced',
    format: 'Tutorial',
    thumbnail_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    source_url: 'https://youtube.com/watch?v=java_graalvm_native',
    duration_seconds: 50,
    educational_value: 88,
    hype_score: 25,
    is_candidate: true,
    created_at: new Date('2026-08-17T13:15:00Z').toISOString(),
  },

  // --- WebDev Candidates ---
  {
    id: '30000000-0000-0000-0000-000000000019',
    title: 'React Server Components vs Client Components: The Real Mental Model',
    description: 'Zero-bundle-size server components, server action serialization, and streaming SSR.',
    transcript: 'React Server Components run exclusively on the server and send a serialized JSON component tree to the client. This keeps heavy Markdown and DB libraries completely out of the client JavaScript bundle.',
    category: 'WebDev',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    source_url: 'https://youtube.com/watch?v=web_rsc_mental_model',
    duration_seconds: 46,
    educational_value: 89,
    hype_score: 28,
    is_candidate: true,
    created_at: new Date('2026-08-17T13:30:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000020',
    title: 'Database Indexing: B-Tree vs Hash vs GIN in Postgres',
    description: 'PostgreSQL index strategies for JSONB, full-text search, and range queries.',
    transcript: 'B-Tree is the default for equality and range filters. Hash indexes only support exact match equality. GIN (Generalized Inverted Index) is mandatory when querying JSONB arrays and tsvector full text.',
    category: 'WebDev',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    source_url: 'https://youtube.com/watch?v=web_postgres_indexing',
    duration_seconds: 48,
    educational_value: 93,
    hype_score: 14,
    is_candidate: true,
    created_at: new Date('2026-08-17T13:45:00Z').toISOString(),
  },

  // --- Hardware & Systems Candidates ---
  {
    id: '30000000-0000-0000-0000-000000000021',
    title: 'CPU Cache Hierarchy: L1, L2, L3 and Cache Miss Latencies',
    description: 'How memory locality and cache lines affect algorithmic runtime faster than Big-O analysis.',
    transcript: 'L1 cache access takes ~1 nanosecond. Main DRAM memory takes ~100 nanoseconds. Writing cache-friendly sequential array structures often outperforms linked node pointers by 10x due to prefetching.',
    category: 'Hardware',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    source_url: 'https://youtube.com/watch?v=hw_cpu_cache_lines',
    duration_seconds: 52,
    educational_value: 94,
    hype_score: 11,
    is_candidate: true,
    created_at: new Date('2026-08-17T14:00:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000022',
    title: 'How GPUs Execute Matrix Multiplication (CUDA Warps)',
    description: 'SIMT (Single Instruction Multiple Threads) execution and shared memory optimization in CUDA.',
    transcript: 'GPUs achieve massive throughput via thousands of cores executing warps of 32 threads in lockstep. Utilizing shared on-chip memory tiling is the key to preventing memory bandwidth saturation.',
    category: 'Hardware',
    difficulty: 'Advanced',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1591488320449-011701bb6704?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4',
    source_url: 'https://youtube.com/watch?v=hw_gpu_cuda_warps',
    duration_seconds: 56,
    educational_value: 93,
    hype_score: 16,
    is_candidate: true,
    created_at: new Date('2026-08-17T14:15:00Z').toISOString(),
  },

  // --- Career / Practical Engineering Candidates ---
  {
    id: '30000000-0000-0000-0000-000000000023',
    title: 'How Senior Engineers Write RFCs and Design Documents',
    description: 'Framework for technical trade-off evaluation, non-functional requirements, and rollout strategies.',
    transcript: 'Code is the easiest part of software engineering. Great engineering design docs clearly outline alternatives considered, security implications, data migration plans, and rollback procedures.',
    category: 'Career',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    source_url: 'https://youtube.com/watch?v=career_rfcs_architecture',
    duration_seconds: 45,
    educational_value: 86,
    hype_score: 18,
    is_candidate: true,
    created_at: new Date('2026-08-17T14:30:00Z').toISOString(),
  },
  {
    id: '30000000-0000-0000-0000-000000000024',
    title: 'Debugging Production Incidents: Real Post-Mortem Walkthrough',
    description: 'Root cause analysis of a cascading failure in a distributed microservices architecture.',
    transcript: 'When a database connection pool exhausted during peak traffic, health checks failed and triggered cascading restarts. We analyze the fix: circuit breakers, jittered exponential backoffs, and load shedding.',
    category: 'Career',
    difficulty: 'Intermediate',
    format: 'Explainer',
    thumbnail_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&auto=format&fit=crop&q=80',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    source_url: 'https://youtube.com/watch?v=career_incident_postmortem',
    duration_seconds: 50,
    educational_value: 91,
    hype_score: 14,
    is_candidate: true,
    created_at: new Date('2026-08-17T14:45:00Z').toISOString(),
  }
];

export const ALL_SEEDED_REELS = [...SEED_INTERACTION_REELS, ...SEED_CANDIDATE_REELS];
